# frozen_string_literal: true

require "bundler/setup"
require "scampi"
require "a2a"
require "a2a/sse"
require "a2a/store"
require "console"
require "securerandom"
require "async"

# ─── Agent Card ────────────────────────────────────────────────────────

agent_card = {
  "name"               => "Code Generator",
  "description"        => "Streams generated code files as chunked artifacts.",
  "version"            => "1.0.0",
  "supportedInterfaces" => [
    {
      "url"             => "http://localhost:9292/a2a",
      "protocolBinding" => "JSONRPC",
      "protocolVersion" => "1.0",
    },
    {
      "url"             => "http://localhost:9292",
      "protocolBinding" => "HTTP+JSON",
      "protocolVersion" => "1.0",
    },
  ],
  "capabilities" => {
    "streaming"         => true,
    "pushNotifications" => false,
  },
  "defaultInputModes"  => ["text/plain"],
  "defaultOutputModes" => ["text/plain", "application/json"],
  "skills" => [
    {
      "id"          => "codegen",
      "name"        => "Code Generator",
      "description" => "Generates code files for a given topic, streaming each file in chunks.",
      "tags"        => ["code", "streaming", "generator"],
      "examples"    => ["Generate a web app", "Create a REST API"],
    },
  ],
}

# ─── Helpers ──────────────────────────────────────────────────────────

extract_text = ->(message) {
  parts = message.respond_to?(:parts) ? message.parts : (message["parts"] || [])
  parts.filter_map { |p| p.respond_to?(:text) ? p.text : p["text"] }.join("\n")
}

now_ts = -> { Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%3NZ") }

# Simulated code files — each split into chunks for streaming
CODE_FILES = {
  "index.html" => [
    "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n",
    "  <title>Generated App</title>\n  <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n",
    "<body>\n  <div id=\"app\"></div>\n  <script src=\"app.js\"></script>\n</body>\n</html>",
  ],
  "style.css" => [
    "/* Generated styles */\n* { margin: 0; padding: 0; box-sizing: border-box; }\n\n",
    "body {\n  font-family: system-ui, sans-serif;\n  background: #f5f5f5;\n  color: #333;\n}\n\n",
    "#app {\n  max-width: 800px;\n  margin: 2rem auto;\n  padding: 1rem;\n  background: white;\n  border-radius: 8px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}",
  ],
  "app.js" => [
    "// Generated application\n'use strict';\n\n",
    "const App = {\n  init() {\n    const el = document.getElementById('app');\n",
    "    el.innerHTML = '<h1>Hello, World!</h1><p>Generated by Code Generator Agent</p>';\n  }\n};\n\n",
    "document.addEventListener('DOMContentLoaded', () => App.init());",
  ],
}

# ─── Store ────────────────────────────────────────────────────────────

sqlite_store = A2A::Store::SQLite.new(path: "codegen.db")

# ─── Agent ────────────────────────────────────────────────────────────

agent = A2A::Agent.new do

  # ── SendStreamingMessage ─────────────────────────────────────────────
  #
  # Streams multiple code files as separate artifacts, each in chunks.
  # Event sequence for each file:
  #   artifactUpdate { append: false, lastChunk: false }  — first chunk
  #   artifactUpdate { append: true,  lastChunk: false }  — middle chunks
  #   artifactUpdate { append: true,  lastChunk: true  }  — final chunk
  #
  on "SendStreamingMessage" do |request|
    msg = request.message
    text = extract_text.(msg)

    context_id = msg.respond_to?(:context_id) ? msg.context_id : msg["contextId"]
    context_id = context_id.to_s.empty? ? SecureRandom.uuid : context_id
    task_id    = SecureRandom.uuid

    store.create(task_id, context_id)
    store.add_message(task_id, {
      "messageId" => (msg.respond_to?(:message_id) ? msg.message_id : msg["messageId"]) || SecureRandom.uuid,
      "role"      => "ROLE_USER",
      "parts"     => [{ "text" => text }],
    })
    store.update_state(task_id, "TASK_STATE_WORKING")

    s = stream

    Async do
      sleep 0.05

      # Event 1: initial task snapshot
      s.event({
        "task" => {
          "id"        => task_id,
          "contextId" => context_id,
          "status"    => { "state" => "TASK_STATE_WORKING", "timestamp" => now_ts.() },
        },
      })

      # Stream each file as a separate artifact with multiple chunks
      CODE_FILES.each_with_index do |(filename, chunks), file_idx|
        artifact_id = SecureRandom.uuid

        chunks.each_with_index do |chunk_text, chunk_idx|
          is_first = chunk_idx == 0
          is_last  = chunk_idx == chunks.length - 1

          sleep 0.05  # simulate progressive generation

          s.event({
            "artifactUpdate" => {
              "taskId"    => task_id,
              "contextId" => context_id,
              "artifact"  => {
                "artifactId"  => artifact_id,
                "name"        => filename,
                "description" => "Generated file: #{filename}",
                "parts"       => [{ "text" => chunk_text }],
              },
              "append"    => !is_first,
              "lastChunk" => is_last,
            },
          })
        end

        # Status update between files
        if file_idx < CODE_FILES.size - 1
          s.event({
            "statusUpdate" => {
              "taskId"    => task_id,
              "contextId" => context_id,
              "status"    => {
                "state"     => "TASK_STATE_WORKING",
                "timestamp" => now_ts.(),
                "message"   => {
                  "messageId" => SecureRandom.uuid,
                  "role"      => "ROLE_AGENT",
                  "parts"     => [{ "text" => "Generated #{filename}, working on next file..." }],
                },
              },
            },
          })
        end
      end

      # Persist final artifacts to the store (assembled from chunks)
      CODE_FILES.each do |filename, chunks|
        store.add_artifact(task_id, {
          "artifactId" => SecureRandom.uuid,
          "name"       => filename,
          "parts"      => [{ "text" => chunks.join }],
        })
      end

      store.add_message(task_id, {
        "messageId" => SecureRandom.uuid,
        "role"      => "ROLE_AGENT",
        "parts"     => [{ "text" => "Generated #{CODE_FILES.size} files: #{CODE_FILES.keys.join(", ")}" }],
      })

      # Final status: completed
      store.update_state(task_id, "TASK_STATE_COMPLETED")
      s.event({
        "statusUpdate" => {
          "taskId"    => task_id,
          "contextId" => context_id,
          "status"    => { "state" => "TASK_STATE_COMPLETED", "timestamp" => now_ts.() },
        },
      })

      s.finish
    rescue => e
      Console.error("SendStreamingMessage") { e.full_message }
      s.finish
    end
  end

  # ── SendMessage (non-streaming fallback) ─────────────────────────────
  on "SendMessage" do |request|
    msg = request.message
    text = extract_text.(msg)

    context_id = msg.respond_to?(:context_id) ? msg.context_id : msg["contextId"]
    context_id = context_id.to_s.empty? ? SecureRandom.uuid : context_id
    task_id    = SecureRandom.uuid

    store.create(task_id, context_id)
    store.add_message(task_id, {
      "messageId" => (msg.respond_to?(:message_id) ? msg.message_id : msg["messageId"]) || SecureRandom.uuid,
      "role"      => "ROLE_USER",
      "parts"     => [{ "text" => text }],
    })

    # Generate all files synchronously
    CODE_FILES.each do |filename, chunks|
      store.add_artifact(task_id, {
        "artifactId" => SecureRandom.uuid,
        "name"       => filename,
        "parts"      => [{ "text" => chunks.join }],
      })
    end

    store.add_message(task_id, {
      "messageId" => SecureRandom.uuid,
      "role"      => "ROLE_AGENT",
      "parts"     => [{ "text" => "Generated #{CODE_FILES.size} files: #{CODE_FILES.keys.join(", ")}" }],
    })
    store.complete(task_id, nil)

    task = store.get(task_id)
    A2A::Schema["Send Message Response"].new(
      task: {
        "id"        => task[:id],
        "contextId" => task[:context_id],
        "status"    => { "state" => task[:state], "timestamp" => task[:updated_at] },
        "artifacts" => task[:artifacts],
        "history"   => task[:history],
      }
    )
  end

  # ── GetTask ──────────────────────────────────────────────────────────
  on "GetTask" do |request|
    id = request.id
    task = store.get(id)
    raise A2A::TaskNotFoundError.new(id) unless task

    A2A::Schema["Task"].new(
      id:         task[:id],
      context_id: task[:context_id],
      status:     { "state" => task[:state], "timestamp" => task[:updated_at] },
      artifacts:  task[:artifacts],
    )
  end
end

# ─── Boot ──────────────────────────────────────────────────────────────

app = A2A::Server.new(agent_card: agent_card, store: sqlite_store)
app.register(agent)

Console.info(self) { "Code Generator starting..." }
Console.info(self) { "Streaming artifacts example: chunked files with append/lastChunk" }

run app
