# frozen_string_literal: true

require "bundler/setup"
require "a2a"
require "a2a/sse"
require "a2a/store"
require "a2a/middleware"
require "console"
require "securerandom"
require "async"
require "yaml"

agent_card = YAML.safe_load_file(File.join(__dir__, "agent_card.yml"))

now_ts = -> { Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%3NZ") }

# Simulated code files — each split into chunks for streaming
CODE_FILES = {
  "index.html" => [
    "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n",
    "  <title>Generated App</title>\n  <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n",
    "<body>\n  <div id=\"app\"></div>\n  <script src=\"app.js\"></script>\n</body>\n</html>",
  ],
  "style.css" => [
    "/* Generated styles */\n* { margin: 0; padding: 0; box-sizing: border-box; }\n\n",
    "body {\n  font-family: system-ui, sans-serif;\n  background: #f5f5f5;\n  color: #333;\n}\n\n",
    "#app {\n  max-width: 800px;\n  margin: 2rem auto;\n  padding: 1rem;\n  background: white;\n  border-radius: 8px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}",
  ],
  "app.js" => [
    "// Generated application\n'use strict';\n\n",
    "const App = {\n  init() {\n    const el = document.getElementById('app');\n",
    "    el.innerHTML = '<h1>Hello, World!</h1><p>Generated by Code Generator Agent</p>';\n  }\n};\n\n",
    "document.addEventListener('DOMContentLoaded', () => App.init());",
  ],
}

sqlite_store = A2A::Store::SQLite.new(path: "codegen.db")

agent = A2A::Agent.new do

  # Streams multiple code files as separate artifacts, each in chunks.
  # Event sequence for each file:
  #   artifactUpdate { append: false, lastChunk: false }  — first chunk
  #   artifactUpdate { append: true,  lastChunk: false }  — middle chunks
  #   artifactUpdate { append: true,  lastChunk: true  }  — final chunk
  #
  on "SendStreamingMessage" do
    use A2A::Middleware::SSEStream
    use A2A::Middleware::ExtractMessage
    respond_with -> (env) {
      request = env["a2a.request"]
      msg = request.message
      text = env["a2a.message"]

      context_id = msg.context_id
      context_id = context_id.to_s.empty? ? SecureRandom.uuid : context_id
      task_id    = SecureRandom.uuid

      sqlite_store.create(task_id, context_id)
      sqlite_store.add_message(task_id, {
        "messageId" => msg.message_id || SecureRandom.uuid,
        "role"      => "ROLE_USER",
        "parts"     => [{ "text" => text }],
      })
      sqlite_store.update_state(task_id, "TASK_STATE_WORKING")

      env["a2a.stream"].open(task_id: task_id, context_id: context_id) do |s|
        sleep 0.05

        # Event 1: initial task snapshot
        s.task(status: { state: "TASK_STATE_WORKING", timestamp: now_ts.() })

        # Stream each file as a separate artifact with multiple chunks
        CODE_FILES.each_with_index do |(filename, chunks), file_idx|
          artifact_id = SecureRandom.uuid

          chunks.each_with_index do |chunk_text, chunk_idx|
            is_first = chunk_idx == 0
            is_last  = chunk_idx == chunks.length - 1

            sleep 0.05  # simulate progressive generation

            s.artifact_update(
              artifact: {
                artifact_id: artifact_id,
                name:        filename,
                description: "Generated file: #{filename}",
                parts:       [{ text: chunk_text }],
              },
              append:     !is_first,
              last_chunk: is_last,
            )
          end

          # Status update between files
          if file_idx < CODE_FILES.size - 1
            s.status_update(
              status: {
                state:     "TASK_STATE_WORKING",
                timestamp: now_ts.(),
                message:   {
                  message_id: SecureRandom.uuid,
                  role:       "ROLE_AGENT",
                  parts:      [{ text: "Generated #{filename}, working on next file..." }],
                },
              },
            )
          end
        end

        # Persist final artifacts to the store (assembled from chunks)
        CODE_FILES.each do |filename, chunks|
          sqlite_store.add_artifact(task_id, {
            "artifactId" => SecureRandom.uuid,
            "name"       => filename,
            "parts"      => [{ "text" => chunks.join }],
          })
        end

        sqlite_store.add_message(task_id, {
          "messageId" => SecureRandom.uuid,
          "role"      => "ROLE_AGENT",
          "parts"     => [{ "text" => "Generated #{CODE_FILES.size} files: #{CODE_FILES.keys.join(", ")}" }],
        })

        # Final status: completed
        sqlite_store.update_state(task_id, "TASK_STATE_COMPLETED")
        s.status_update(status: { state: "TASK_STATE_COMPLETED", timestamp: now_ts.() })
      end
    }
  end

  on "SendMessage" do
    use A2A::Middleware::ExtractMessage
    respond_with -> (env) {
      request = env["a2a.request"]
      msg = request.message
      text = env["a2a.message"]

      context_id = msg.context_id
      context_id = context_id.to_s.empty? ? SecureRandom.uuid : context_id
      task_id    = SecureRandom.uuid

      sqlite_store.create(task_id, context_id)
      sqlite_store.add_message(task_id, {
        "messageId" => msg.message_id || SecureRandom.uuid,
        "role"      => "ROLE_USER",
        "parts"     => [{ "text" => text }],
      })

      # Generate all files synchronously
      CODE_FILES.each do |filename, chunks|
        sqlite_store.add_artifact(task_id, {
          "artifactId" => SecureRandom.uuid,
          "name"       => filename,
          "parts"      => [{ "text" => chunks.join }],
        })
      end

      sqlite_store.add_message(task_id, {
        "messageId" => SecureRandom.uuid,
        "role"      => "ROLE_AGENT",
        "parts"     => [{ "text" => "Generated #{CODE_FILES.size} files: #{CODE_FILES.keys.join(", ")}" }],
      })
      sqlite_store.complete(task_id, nil)

      task = sqlite_store.get(task_id)
      A2A::Schema["Send Message Response"].new(
        task: {
          "id"        => task[:id],
          "contextId" => task[:context_id],
          "status"    => { "state" => task[:state], "timestamp" => task[:updated_at] },
          "artifacts" => task[:artifacts],
          "history"   => task[:history],
        }
      )
    }
  end

  on "GetTask" do
    use A2A::Middleware::FetchTaskOrRaise, store: sqlite_store
    respond_with -> (env) {
      task = env["a2a.task"]

      A2A::Schema["Task"].new(
        id:         task[:id],
        context_id: task[:context_id],
        status:     { "state" => task[:state], "timestamp" => task[:updated_at] },
        artifacts:  task[:artifacts],
      )
    }
  end
end

app = A2A::Server.new(agent_card: agent_card)
app.register(agent)

Console.info(self) { "Code Generator starting..." }
Console.info(self) { "Streaming artifacts example: chunked files with append/lastChunk" }

run app
