services:
  agent:
    build: ./agent
    restart: unless-stopped
    ports:
      - 9292:9292
    depends_on:
      - receiver

  receiver:
    build: ./receiver
    restart: unless-stopped
    ports:
      - 9293:9293
